
DEFAULT_SERVICE_IDENTITY = u'+default+'

CALLBACK_FRIEND_INVITE_RESULT = 1
CALLBACK_FRIEND_INVITED = 2
CALLBACK_FRIEND_BROKE_UP = 4
CALLBACK_FRIEND_IN_REACH = 512
CALLBACK_FRIEND_OUT_OF_REACH = 1024
CALLBACK_FRIEND_IS_IN_ROLES = 2048
CALLBACK_FRIEND_UPDATE = 8192
CALLBACK_FRIEND_LOCATION_FIX = 65536
CALLBACK_FRIEND_REGISTER = 131072
CALLBACK_FRIEND_REGISTER_RESULT = 262144
CALLBACK_MESSAGING_RECEIVED = 8
CALLBACK_MESSAGING_POKE = 16
CALLBACK_MESSAGING_ACKNOWLEDGED = 128
CALLBACK_MESSAGING_FLOW_MEMBER_RESULT = 64
CALLBACK_MESSAGING_FORM_ACKNOWLEDGED = 32
CALLBACK_MESSAGING_NEW_CHAT_MESSAGE = 4096
CALLBACK_MESSAGING_CHAT_DELETED = 32768
CALLBACK_MESSAGING_LIST_CHAT_MESSAGES = 1048576
CALLBACK_SYSTEM_API_CALL = 256
CALLBACK_SYSTEM_SERVICE_DELETED = 16384
CALLBACK_SYSTEM_BRANDINGS_UPDATED = 524288

CALLBACKS = (CALLBACK_FRIEND_INVITE_RESULT, CALLBACK_FRIEND_INVITED, CALLBACK_FRIEND_BROKE_UP,
             CALLBACK_MESSAGING_RECEIVED, CALLBACK_MESSAGING_POKE, CALLBACK_MESSAGING_FLOW_MEMBER_RESULT,
             CALLBACK_MESSAGING_ACKNOWLEDGED, CALLBACK_MESSAGING_FORM_ACKNOWLEDGED, CALLBACK_SYSTEM_API_CALL,
             CALLBACK_SYSTEM_SERVICE_DELETED, CALLBACK_SYSTEM_BRANDINGS_UPDATED,
             CALLBACK_FRIEND_IN_REACH, CALLBACK_FRIEND_OUT_OF_REACH, CALLBACK_FRIEND_IS_IN_ROLES,
             CALLBACK_FRIEND_UPDATE, CALLBACK_MESSAGING_NEW_CHAT_MESSAGE, CALLBACK_MESSAGING_CHAT_DELETED,
             CALLBACK_FRIEND_LOCATION_FIX, CALLBACK_FRIEND_REGISTER, CALLBACK_FRIEND_REGISTER_RESULT)

ORGANIZATION_TYPE_UNSPECIFIED = -1
ORGANIZATION_TYPE_NON_PROFIT = 1
ORGANIZATION_TYPE_PROFIT = 2
ORGANIZATION_TYPE_CITY = 3
ORGANIZATION_TYPE_EMERGENCY = 4
ORGANIZATION_TYPES = [ORGANIZATION_TYPE_UNSPECIFIED, ORGANIZATION_TYPE_NON_PROFIT, ORGANIZATION_TYPE_PROFIT,
                      ORGANIZATION_TYPE_CITY, ORGANIZATION_TYPE_EMERGENCY]
